import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/navbar/navbar";
import { Sidebar } from "./components/sidebar/sidebar";
import { Footer } from "./components/footer/footer";
import { AuthProvider } from "./hooks/useAuth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <div className="w-full min-h-screen bg-gradient-to-b from-sky-100 to-pink-100 flex flex-col">
            <div className="fixed top-0 left-0 w-full z-50">
              <Navbar />
            </div>
            <div className="flex flex-1 pt-[72px]">
              {/* offset for navbar height */}
              {/* Fixed Sidebar */}
              <aside className="fixed hidden md:block top-[72px] left-0 h-[calc(100vh-72px)] w-1/5 z-40">
                <Sidebar />
              </aside>
              {/* Scrollable main content */}
              <main className="flex flex-col ml-[0%] md:ml-[20%] flex-1 overflow-y-auto">
                {children}
                <Footer />
              </main>
            </div>
          </div>
        </body>
      </AuthProvider>
    </html>
  );
}
